version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: itemsdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      start_period: 20s
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://dev:dev@db:3306/itemsdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  mysqldata:
