apiVersion: v1
kind: Namespace
metadata:
  name: devops-poc

---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: dev
            - name: MYSQL_USER
              value: dev
            - name: MYSQL_PASSWORD
              value: dev
            - name: MYSQL_DATABASE
              value: itemsdb
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}   # ⚠ temporary storage, replace with PVC for persistence

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devops-poc
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tanushri0109/devops-poc:v1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mysql+pymysql://dev:dev@mysql:3306/itemsdb"

---
# API Service (NodePort for external access)
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: devops-poc
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 8000 # Container port
      nodePort: 30080 # Fixed NodePort (must be between 30000-32767)
  type: NodePort
