apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: items-api-rules
  labels:
    role: alert-rules
spec:
  groups:
  - name: items-api.rules
    rules:
    - alert: ItemsAPIHighLatency
      expr: histogram_quantile(0.95, sum(rate(request_processing_seconds_bucket[5m])) by (le)) > 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High P95 latency for Items API"
        description: "P95 latency {{ $value }}s"

    - alert: ItemsAPIDown
      expr: absent(up{job="kubernetes-service-endpoints", kubernetes_service_name="items-api"} == 1)
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Items API down"
        description: "No endpoints are up for items-api"
