apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: items-api-sm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: items-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
