name: Terraform Destroy EKS

on:
  workflow_dispatch: # Manual trigger only

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-destroy:
    name: Destroy EKS Cluster
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./Infra

      # Step 5: Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./Infra
